# D:\DTN2507_Huynh_Chi_Van1\demo_connectdatabase\src\main\resources
# Database Configuration
db.url=jdbc:mysql://localhost:3307/testingsystem
db.user=root
db.password=
db.driver=com.mysql.cj.jdbc.Driver